# Generated by Django 4.2.7 on 2023-12-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='images/product')),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('features', models.CharField(max_length=1000)),
                ('discount', models.IntegerField()),
                ('category', models.CharField(choices=[('l', 'Laptops'), ('m', 'Mobiles'), ('c', 'Cameras and Photography'), ('h', 'Headphones and Accessories'), ('p', 'Powerbanks and Chargers'), ('a', 'Accessories')], default='l', max_length=100)),
            ],
        ),
    ]
